name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SBT_OPTS: -Xms256m -Xmx756G -XX:+CMSClassUnloadingEnabled -XX:+UseSerialGC -XX:MaxMetaspaceSize=2G
  DISABLE_SCALAFMT: true

jobs:
  sbt-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-${{ hashFiles('build.sbt') }}
    - name: Run tests
      run: sbt test
  compile-microsite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11
    - name: Update package descriptions
      run: sudo apt update
    - name: Install jekyll
      run: sudo apt -y install jekyll
    - uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.sbt
          ~/.ivy2/cache
        key: ${{ runner.os }}-${{ hashFiles('build.sbt') }}
    - name: Compile microsite
      run: sbt docs/makeMicrosite

